[package]
name = "game-of-hexlife"
version = "0.1.0"
authors = ["RichoDemus <git@richodemus.com>"]
edition = "2018"

[dependencies]
rand = { version = "0.7.3", features = ["stdweb"] }
quicksilver = { version = "0.4.0", default-features = true, features = ["stdweb"]}
